# Copy this file as "config.yaml", and fill in the values as appropriate.
# ------------------------------------------------------------------------------

# Whether to log debug events from the discord.js client
debug: true

# Your Discord bot token. See: https://discordapp.com/developers/applications/me
token:

# Your Discord client ID, as a string.
clientId:

# The Discord guild ID to specifically register commands to, as a string array
# null for universal registration
guildIds: #null
  - '000000000000000000'

# The channel ID where a loaded message will be displayed on startup, as a string.
# Leave as null to disable
loadedMessageId: null

# The ID of the one user who is allowed to clear all registered commands (for testing purposes), as a string.
# Leave as null to disable
unregisterAllId: null

# Whether to allow only listed bots
allowlistEnabled: false

# List of bots (folder names under src/bots/)
# should be an array of strings
allowlist:
  - PingBot

# Whether the process should exit if the discord.js WebSocket has an issue and reports a zombie connection
# Beware login limits (1000/day?), this is only here as a workaround for my bot online availability problems
# This will be removed when this is fixed: https://github.com/discordjs/discord.js/issues/8486
exitOnWsZombie: false
